/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-05-05 12:57:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class BookAppointment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1746446599104L));
    _jspx_dependants.put("/Header1.jsp", Long.valueOf(1746446599247L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Stylish Appointment Form</title>\r\n");
      out.write("    <style>\r\n");
      out.write("       \r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            \r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background-image:url('https://img.freepik.com/premium-photo/generative-ai-cat-paws-stethoscope-isolated-blue-background-banner-with-copy-space_93150-35877.jpg?semt=ais_hybrid');\r\n");
      out.write("            background-position:fixed;\r\n");
      out.write("            background-repeat:no-repeat;\r\n");
      out.write("            background-size:1500px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .form-container {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 500px;\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            margin-left:750px;\r\n");
      out.write("            margin-bottom:30px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 15px 30px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("            animation: slide-in 0.6s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        @keyframes slide-in {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(20px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .form-container h2::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: -8px;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            height: 3px;\r\n");
      out.write("            background: linear-gradient(135deg, #fbc531, #f7e441);\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input[type=\"text\"],\r\n");
      out.write("        .form-group input[type=\"date\"],\r\n");
      out.write("        .form-group select {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        .form-group input:focus,\r\n");
      out.write("        .form-group select:focus {\r\n");
      out.write("            border-color: #fbc531;\r\n");
      out.write("            box-shadow: 0 0 8px rgba(251, 197, 49, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .form-group select {\r\n");
      out.write("            appearance: none;\r\n");
      out.write("            background: url('data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\"%3E%3Cpath d=\"M7 10l5 5 5-5z\"%3E%3C/path%3E%3C/svg%3E') no-repeat right 15px center;\r\n");
      out.write("            background-size: 14px;\r\n");
      out.write("            padding-right: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .submit-btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            background: linear-gradient(135deg, #fbc531, #f7e441);\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(251, 197, 49, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submit-btn:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        .response {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            background: #fff8e7;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            border: 1px solid #f7e441;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .response h3 {\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("            color: #fbc531;\r\n");
      out.write("        }\r\n");
      out.write("      #msg {\r\n");
      out.write("    padding: 12px 20px;\r\n");
      out.write("    background-color: #d1ffd1;\r\n");
      out.write("    color: #1a7e1a;\r\n");
      out.write("    border: 1px solid #00a300;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: 20px auto;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("    width: 80%;\r\n");
      out.write("    box-shadow: 0px 5px 10px rgba(0, 163, 0, 0.2);\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;300&display=swap');\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 15px 30px;\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .logo img {\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    width: auto;\r\n");
      out.write("    margin-left:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul li a {\r\n");
      out.write("    padding: 10px 15px;\r\n");
      out.write("    font-size:16px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    \r\n");
      out.write("    color: #333;\r\n");
      out.write("    border-bottom: 2px solid transparent;\r\n");
      out.write("    transition: color 0.3s, border-color 0.3s, transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul li a:hover {\r\n");
      out.write("    color: #007bff;\r\n");
      out.write("    border-color: #007bff;\r\n");
      out.write("    transform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right i {\r\n");
      out.write("    font-size: 26px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right .rel {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right .rel .num {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: -10px;\r\n");
      out.write("    background-color: red;\r\n");
      out.write("    color: white;\r\n");
      out.write("    width: 16px;\r\n");
      out.write("    height: 16px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uname {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("   \r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("button.btn {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.btn:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    header {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu ul {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        gap: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .header_right {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu ul li a {\r\n");
      out.write("        padding: 12px 20px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <a href=\"Home1.jsp\">\r\n");
      out.write("            <img src=\"Images/Logo.png\" alt=\"Logo\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            ");
 if (session.getAttribute("uname") != null) { 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Home1.jsp\">Home</a></li>\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Contact.jsp\">Contact</a></li>\r\n");
      out.write("\r\n");
      out.write("                <!-- Admin-specific Menu Items (id = 1) -->\r\n");
      out.write("                ");
 if ("1".equals(session.getAttribute("id"))) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"myorder.jsp\">My Orders</a></li>\r\n");
      out.write("                    <li><a href=\"Admin.jsp\">Dashboard</a></li>\r\n");
      out.write("                    <li><a href=\"BookedProducts.jsp\">Booked Products</a></li>\r\n");
      out.write("                    <li><a href=\"UserReviews.jsp\">User Reviews</a></li>\r\n");
      out.write("                    <li><a href=\"AppList.jsp\">Appointment List</a></li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                 \r\n");
      out.write("                    <li><a href=\"HealthAssist.jsp\">Health Assistance</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"register?logout=yes\">Logout</a></li>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Home1.jsp\">Home</a></li>\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("                <li><a href=\"Registration.jsp\">Register</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("       ");
 if (session.getAttribute("uname") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"header_right\">\r\n");
      out.write("        <a href=\"Wishlist.jsp\"><i class=\"fa fa-heart\"></i></a>\r\n");
      out.write("        <a href=\"Search.jsp\"><i class=\"fa-solid fa-magnifying-glass\"></i></a>\r\n");
      out.write("        <div class=\"rel\">\r\n");
      out.write("            <a href=\"cart.jsp\"><i class=\"fa-solid fa-cart-shopping\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("            <div class=\"uname\">\r\n");
      out.write("                <i class=\"fa fa-user-circle\" style=\"margin-right: 5px;\"></i>\r\n");
      out.write("                ");
      out.print( session.getAttribute("uname") );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"form-container\">\r\n");
      out.write("    ");
 if (request.getAttribute("status") != null) { 
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        alert(\"");
      out.print( request.getAttribute("status") );
      out.write("\");\r\n");
      out.write("    </script>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <h2>Book an Appointment</h2>\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("        <form action=\"Schedule\" method=\"post\">\r\n");
      out.write("       \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"name\">Name:</label>\r\n");
      out.write("                <input type=\"text\" id=\"name\" name=\"p_name\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"phone\">Phone:</label>\r\n");
      out.write("                <input type=\"text\" id=\"phone\" name=\"phone\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"appointmentDate\">Appointment Date:</label>\r\n");
      out.write("                <input type=\"date\" id=\"appointmentDate\" name=\"appointmentDate\"  min=\"");
      out.print( new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()) );
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"disease\">Select Disease:</label>\r\n");
      out.write("                <select id=\"disease\" name=\"disease\" required>\r\n");
      out.write("                    <option value=\"\" disabled selected>Select disease</option>\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <optgroup label=\"Dog Diseases\">\r\n");
      out.write("                        <option value=\"Ringworm\">Ringworm</option>\r\n");
      out.write("                        <option value=\"Parvovirus\">Parvovirus</option>\r\n");
      out.write("                        <option value=\"Kennel Cough\">Kennel Cough</option>\r\n");
      out.write("                        <option value=\"Heartworm\">Heartworm</option>\r\n");
      out.write("                    </optgroup>\r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                    <optgroup label=\"Cat Diseases\">\r\n");
      out.write("                       \r\n");
      out.write("                        <option value=\"Cat flu\">Cat Flu</option>\r\n");
      out.write("                        <option value=\"Rabies\">Rabies</option>\r\n");
      out.write("                        <option value=\"Dental issue\">Dental issue</option>\r\n");
      out.write("                        <option value=\"Kidney Disease\">Kidney Disease</option>\r\n");
      out.write("                    </optgroup>\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <optgroup label=\"Bird Diseases\">\r\n");
      out.write("                        <option value=\"Parrot fever\">Parrot fever</option>\r\n");
      out.write("                        <option value=\"Avian Influenza\">Avian Influenza</option>\r\n");
      out.write("                        <option value=\"Fungal infection\">Fungal infection</option>\r\n");
      out.write("                        \r\n");
      out.write("                        <option value=\"Polyoma virus\">Polyoma virus Disease</option>\r\n");
      out.write("                    </optgroup>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" class=\"submit-btn\">Submit</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <!-- Processing Submitted Data -->\r\n");
      out.write("        ");

            String name = request.getParameter("name");
            String phone = request.getParameter("phone");
            String appointmentDate = request.getParameter("appointmentDate");
            String disease = request.getParameter("disease");

            if (name != null && phone != null && appointmentDate != null && disease != null) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                Date date = dateFormat.parse(appointmentDate);
        
      out.write("\r\n");
      out.write("                <div class=\"response\">\r\n");
      out.write("                    <h3>Appointment Details:</h3>\r\n");
      out.write("                    <p><strong>Name:</strong> ");
      out.print( name );
      out.write("</p>\r\n");
      out.write("                    <p><strong>Phone:</strong> ");
      out.print( phone );
      out.write("</p>\r\n");
      out.write("                    <p><strong>Appointment Date:</strong> ");
      out.print( dateFormat.format(date) );
      out.write("</p>\r\n");
      out.write("                    <p><strong>Disease:</strong> ");
      out.print( disease );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Arial', sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    footer {\r\n");
      out.write("        background-color: black;\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 55px 0;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        justify-content: space-around;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-column {\r\n");
      out.write("        flex: 1;\r\n");
      out.write("        margin: 20px;\r\n");
      out.write("        min-width: 200px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-column h3 {\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        color: #f4d03f;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-column h3::after {\r\n");
      out.write("        content: '';\r\n");
      out.write("        display: block;\r\n");
      out.write("        width: 50px;\r\n");
      out.write("        height: 3px;\r\n");
      out.write("        background-color: #f4d03f;\r\n");
      out.write("        margin-top: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-column ul {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-column ul li {\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-column ul li a {\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        transition: color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-column ul li a:hover {\r\n");
      out.write("        color: #f4d03f;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-column p {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        line-height: 1.8;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter input[type=\"email\"] {\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        width: 75%;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter button {\r\n");
      out.write("        padding: 12px 15px;\r\n");
      out.write("        background-color: #f4d03f;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter button:hover {\r\n");
      out.write("        background-color: #e2b20e;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter {\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-bottom {\r\n");
      out.write("        background-color: #141414;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: #aaa;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        border-top: 1px solid #444;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-bottom a {\r\n");
      out.write("        color: #f4d03f;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-bottom a:hover {\r\n");
      out.write("        text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-column img {\r\n");
      out.write("        width: 150px;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    i{\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    .popular-searches a,a {\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        /* padding: 1px; */\r\n");
      out.write("        transition: color 0.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .popular-searches a:hover {\r\n");
      out.write("        color: #f1cb33;\r\n");
      out.write("        text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    img:hover,i:hover{\r\n");
      out.write("        scale: 1.3;\r\n");
      out.write("        color: #f4d03f;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .popular-searches{\r\n");
      out.write("        margin-left: 60px;\r\n");
      out.write("        margin-right: 60px;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <img src=\"./Images/Logo1.png\" alt=\"Hub4Pets Logo\">\r\n");
      out.write("            <p>Your one-stop destination for all pet supplies and care, because pets deserve the best!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Shop by Category</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"dog.jsp?animal=dogfood\">Dog Food</a></li>\r\n");
      out.write("                <li><a href=\"Cat.jsp?animal=catfood\">Cat Food</a></li>\r\n");
      out.write("                <li><a href=\"Bird.jsp?animal=Birds\">Birds & Fish Supplies</a></li>\r\n");
      out.write("                <li><a href=\"dog.jsp?animal=dogaccessories\">Pet Toys</a></li>\r\n");
      out.write("                <li><a href=\"dog.jsp?animal=doggrooming\">Pet Grooming</a></li>\r\n");
      out.write("                <li><a href=\"dog.jsp?animal=dogtreats\">Pet Treats</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Customer Service</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">Help Center</a></li>\r\n");
      out.write("                <li><a href=\"#\">FAQs</a></li>\r\n");
      out.write("                <li><a href=\"#\">Shipping & Delivery</a></li>\r\n");
      out.write("                <li><a href=\"#\">Returns</a></li>\r\n");
      out.write("                <li><a href=\"#\">Track Your Order</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Get in Touch</h3>\r\n");
      out.write("            <p><i class=\"fa-solid fa-phone\"></i> 080-45678765</p>\r\n");
      out.write("            <p><i class=\"fa-solid fa-envelope\"></i> <a href=\"mailto:support@hub4pets.com\">support@hub4pets.com</a></p>\r\n");
      out.write("            <h3>Follow Us</h3>\r\n");
      out.write("            <div class=\"social-icons\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fa-brands fa-twitter\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa-brands fa-instagram\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa-brands fa-facebook\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa-brands fa-youtube\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Newsletter</h3>\r\n");
      out.write("            <p>Subscribe for pet care tips, special deals, and the latest news.</p>\r\n");
      out.write("            <div class=\"newsletter\">\r\n");
      out.write("                <a href=\"Registration.jsp\"><button type=\"submit\">Signup</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"popular-searches\">\r\n");
      out.write("            <h3>POPULAR SEARCHES</h3>\r\n");
      out.write("            <div>\r\n");
      out.write("                <p>Dog Food</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Collars Leashes Harnesses</a>\r\n");
      out.write("                <a href=\"#\"> | Me-O</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Clothes</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Litter</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Raincoat</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Toys</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Beds</a>\r\n");
      out.write("                <a href=\"#\"> | Veg Dog Food</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Biscuits Cookies</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Dry Food</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Food</a>\r\n");
      out.write("                <a href=\"#\"> | Pet Pharmacy</a>\r\n");
      out.write("                <a href=\"#\"> | Pedigree</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Toys</a>\r\n");
      out.write("                <a href=\"#\"> | Drools</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Grooming</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Carrier</a>\r\n");
      out.write("                <a href=\"#\"> | Dogs Bones Chews</a>\r\n");
      out.write("                <a href=\"#\"> | Pedigree Pro</a>\r\n");
      out.write("                <a href=\"#\"> | Whiskas</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Collars Leashes Harnesses</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Wet Food</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Shampoos & Conditioners</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Carriers Travel Supplies</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Accessories</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Bowls Feeders</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Clothes</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Treats</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Accessories</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Litter Boxes</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Treats</a>\r\n");
      out.write("                <a href=\"#\"> | Farmina</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Leashes</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Kitten Food</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Beds Mats Tents</a>\r\n");
      out.write("                <a href=\"#\"> | Deworming Tablets</a>\r\n");
      out.write("                <a href=\"#\"> | Cat Shampoo & Conditioners</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Fleas & Ticks</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Boots</a>\r\n");
      out.write("                <a href=\"#\"> | Orijen Dog Food</a>\r\n");
      out.write("                <a href=\"#\"> | Acana Dog Food</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Training & Behaviour</a>\r\n");
      out.write("                <a href=\"#\"> | Dog Food Supplements & Vitamins</a></div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"footer-bottom\">\r\n");
      out.write("        <p>&copy; 2024 Hub4Pets Pvt Ltd. All rights reserved. | <a href=\"\">Privacy Policy</a> | <a href=\"#\">Terms &\r\n");
      out.write("            Conditions</a></p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
