/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-05-05 12:57:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Header1.jsp", Long.valueOf(1746446599247L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\" integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <title>ContactUs</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    *{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding:0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    body{\r\n");
      out.write("        background-image: url(https://img.freepik.com/free-photo/beautiful-pet-portrait-dog_23-2149218474.jpg?t=st=1728540361~exp=1728543961~hmac=eb7902ff091ad16c0d309ee28b9e80dce3eb8b6b1b752f9e8a244f52db7a0207&w=900);\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    form{\r\n");
      out.write("        height: 540px;\r\n");
      out.write("        width: 400px;\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.713);\r\n");
      out.write("        box-shadow: 0 0 20px rgb(232, 165, 165);\r\n");
      out.write("        position: relative;\r\n");
      out.write("        margin-top: 40px;\r\n");
      out.write("        margin-left: 850px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        border-top-right-radius: 200px;\r\n");
      out.write("        border-top-left-radius: 200px;\r\n");
      out.write("    }\r\n");
      out.write("    input{\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        border:2px solid rgb(208, 148, 148); \r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    input:focus,button:focus {\r\n");
      out.write("            outline: none; \r\n");
      out.write("            border:2px solid rgb(208, 148, 148); \r\n");
      out.write("            box-shadow: 0 0 10px rgb(208, 145, 145);;\r\n");
      out.write("        }\r\n");
      out.write("        .btn {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: rgb(208, 145, 145);\r\n");
      out.write("            background-color: transparent;\r\n");
      out.write("            border: 2px solid rgb(208, 145, 145);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            transition: color 0.4s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 0;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background-color: rgb(208, 145, 145);\r\n");
      out.write("            transition: width 0.5s;\r\n");
      out.write("            z-index: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover::before,.btn:hover::after {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn span {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;300&display=swap');\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 15px 30px;\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .logo img {\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    width: auto;\r\n");
      out.write("    margin-left:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul li a {\r\n");
      out.write("    padding: 10px 15px;\r\n");
      out.write("    font-size:16px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    \r\n");
      out.write("    color: #333;\r\n");
      out.write("    border-bottom: 2px solid transparent;\r\n");
      out.write("    transition: color 0.3s, border-color 0.3s, transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul li a:hover {\r\n");
      out.write("    color: #007bff;\r\n");
      out.write("    border-color: #007bff;\r\n");
      out.write("    transform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right i {\r\n");
      out.write("    font-size: 26px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right .rel {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right .rel .num {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: -10px;\r\n");
      out.write("    background-color: red;\r\n");
      out.write("    color: white;\r\n");
      out.write("    width: 16px;\r\n");
      out.write("    height: 16px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uname {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("   \r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("button.btn {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.btn:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    header {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu ul {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        gap: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .header_right {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu ul li a {\r\n");
      out.write("        padding: 12px 20px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <a href=\"Home1.jsp\">\r\n");
      out.write("            <img src=\"Images/Logo.png\" alt=\"Logo\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            ");
 if (session.getAttribute("uname") != null) { 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Home1.jsp\">Home</a></li>\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Contact.jsp\">Contact</a></li>\r\n");
      out.write("\r\n");
      out.write("                <!-- Admin-specific Menu Items (id = 1) -->\r\n");
      out.write("                ");
 if ("1".equals(session.getAttribute("id"))) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"myorder.jsp\">My Orders</a></li>\r\n");
      out.write("                    <li><a href=\"Admin.jsp\">Dashboard</a></li>\r\n");
      out.write("                    <li><a href=\"BookedProducts.jsp\">Booked Products</a></li>\r\n");
      out.write("                    <li><a href=\"UserReviews.jsp\">User Reviews</a></li>\r\n");
      out.write("                    <li><a href=\"AppList.jsp\">Appointment List</a></li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                 \r\n");
      out.write("                    <li><a href=\"HealthAssist.jsp\">Health Assistance</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"register?logout=yes\">Logout</a></li>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Home1.jsp\">Home</a></li>\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("                <li><a href=\"Registration.jsp\">Register</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("       ");
 if (session.getAttribute("uname") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"header_right\">\r\n");
      out.write("        <a href=\"Wishlist.jsp\"><i class=\"fa fa-heart\"></i></a>\r\n");
      out.write("        <a href=\"Search.jsp\"><i class=\"fa-solid fa-magnifying-glass\"></i></a>\r\n");
      out.write("        <div class=\"rel\">\r\n");
      out.write("            <a href=\"cart.jsp\"><i class=\"fa-solid fa-cart-shopping\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("            <div class=\"uname\">\r\n");
      out.write("                <i class=\"fa fa-user-circle\" style=\"margin-right: 5px;\"></i>\r\n");
      out.write("                ");
      out.print( session.getAttribute("uname") );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
 String status = (String)request.getAttribute("status"); 
      out.write('\r');
      out.write('\n');
      out.write(' ');
 if(request.getAttribute("status") != null) { 
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            alert(\"");
      out.print( status );
      out.write("\");\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    <form action=\"https://formsubmit.co/vaishnavijoshi292002@gmail.com\" method=\"post\" onsubmit=\"sendEmail();\" reset(); return();>\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <h1 style=\"color: rgb(208, 148, 148); \">ContactUs</h1><br>\r\n");
      out.write("        <input type=\"text\" placeholder=\"Name\" name=\"name\"  value=");
      out.print(session.getAttribute("uname") );
      out.write(" required><br><br>\r\n");
      out.write("        <input type=\"email\" placeholder=\"Email\" name=\"email\" id=\"email\" value=");
      out.print(session.getAttribute("email") );
      out.write(" required><br><br>\r\n");
      out.write("        <input type=\"tel\" placeholder=\"Phone\" name=\"phone\" id=\"phone\" ><br><br>\r\n");
      out.write("        <input type=\"text\" placeholder=\"Subject\"name=\"subject\" required><br><br>\r\n");
      out.write("        <input type=\"text\" placeholder=\"Message\"name=\"message\" required><br><br>\r\n");
      out.write("        <input type=\"submit\" class=\"btn\" name=\"Contact\" value=Contact >\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("      \r\n");
      out.write("    </form>\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
