/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-05-05 13:02:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import com.MVC.Model.Dproduct;
import com.MVC.Model.Registration;

public final class dog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Header1.jsp", Long.valueOf(1746446599247L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.MVC.Model.Dproduct");
    _jspx_imports_classes.add("com.MVC.Model.Registration");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Product List</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Roboto', sans-serif;\r\n");
      out.write("	background-color: #fdf6e3;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 40px 0;\r\n");
      out.write("	background: linear-gradient(90deg, #f9e55e, #f9d04e);\r\n");
      out.write("	border-bottom: 2px solid #f9d04e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header h1 {\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card {\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	border: 2px solid #f9d04e;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	margin: 20px;\r\n");
      out.write("	padding: 25px;\r\n");
      out.write("	width: 350px;\r\n");
      out.write("	transition: transform 0.3s, box-shadow 0.3s;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	box-shadow: 0 6px 20px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-image img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-title {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 15px 0;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	color: #444;\r\n");
      out.write("	font-size: 1.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price {\r\n");
      out.write("	color: #f9d04e;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 1.5em;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-description {\r\n");
      out.write("	font-size: 0.9em;\r\n");
      out.write("	color: #666;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rating {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".average-rating {\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".star {\r\n");
      out.write("	color: #f9d04e;\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".availability, .delivery-info, .return-policy {\r\n");
      out.write("	font-size: 0.9em;\r\n");
      out.write("	color: #666;\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	margin: 15px 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".add-to-cart {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("	background-color: #f9e55e;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 25px;\r\n");
      out.write("	padding: 10px 15px;\r\n");
      out.write("	font-size: 1.2em;\r\n");
      out.write("	transition: background-color 0.3s, transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".add-to-cart:hover {\r\n");
      out.write("	background-color: #f9d04e;\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".quantity-select {\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("	border: 2px solid #f9d04e;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logos {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 180px; /* Adjust as needed for spacing */\r\n");
      out.write("	right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logos img {\r\n");
      out.write("	width: 80px;\r\n");
      out.write("	height: 90px;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-buttons .btn {\r\n");
      out.write("	margin: 0 10px;\r\n");
      out.write("	background-color: #f9e55e;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	border-radius: 25px;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	transition: transform 0.3s, background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-buttons .btn:hover {\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("	background-color: #f9d04e;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;300&display=swap');\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 15px 30px;\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .logo img {\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    width: auto;\r\n");
      out.write("    margin-left:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul li a {\r\n");
      out.write("    padding: 10px 15px;\r\n");
      out.write("    font-size:16px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    \r\n");
      out.write("    color: #333;\r\n");
      out.write("    border-bottom: 2px solid transparent;\r\n");
      out.write("    transition: color 0.3s, border-color 0.3s, transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul li a:hover {\r\n");
      out.write("    color: #007bff;\r\n");
      out.write("    border-color: #007bff;\r\n");
      out.write("    transform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right i {\r\n");
      out.write("    font-size: 26px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right .rel {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right .rel .num {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: -10px;\r\n");
      out.write("    background-color: red;\r\n");
      out.write("    color: white;\r\n");
      out.write("    width: 16px;\r\n");
      out.write("    height: 16px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uname {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("   \r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("button.btn {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.btn:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    header {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu ul {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        gap: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .header_right {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu ul li a {\r\n");
      out.write("        padding: 12px 20px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <a href=\"Home1.jsp\">\r\n");
      out.write("            <img src=\"Images/Logo.png\" alt=\"Logo\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            ");
 if (session.getAttribute("uname") != null) { 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Home1.jsp\">Home</a></li>\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Contact.jsp\">Contact</a></li>\r\n");
      out.write("\r\n");
      out.write("                <!-- Admin-specific Menu Items (id = 1) -->\r\n");
      out.write("                ");
 if ("1".equals(session.getAttribute("id"))) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"myorder.jsp\">My Orders</a></li>\r\n");
      out.write("                    <li><a href=\"Admin.jsp\">Dashboard</a></li>\r\n");
      out.write("                    <li><a href=\"BookedProducts.jsp\">Booked Products</a></li>\r\n");
      out.write("                    <li><a href=\"UserReviews.jsp\">User Reviews</a></li>\r\n");
      out.write("                    <li><a href=\"AppList.jsp\">Appointment List</a></li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                 \r\n");
      out.write("                    <li><a href=\"HealthAssist.jsp\">Health Assistance</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"register?logout=yes\">Logout</a></li>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Home1.jsp\">Home</a></li>\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("                <li><a href=\"Registration.jsp\">Register</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("       ");
 if (session.getAttribute("uname") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"header_right\">\r\n");
      out.write("        <a href=\"Wishlist.jsp\"><i class=\"fa fa-heart\"></i></a>\r\n");
      out.write("        <a href=\"Search.jsp\"><i class=\"fa-solid fa-magnifying-glass\"></i></a>\r\n");
      out.write("        <div class=\"rel\">\r\n");
      out.write("            <a href=\"cart.jsp\"><i class=\"fa-solid fa-cart-shopping\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("            <div class=\"uname\">\r\n");
      out.write("                <i class=\"fa fa-user-circle\" style=\"margin-right: 5px;\"></i>\r\n");
      out.write("                ");
      out.print( session.getAttribute("uname") );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		<h1>Welcome to Our Pet Shop!</h1>\r\n");
      out.write("		<div class=\"nav-buttons\">\r\n");
      out.write("			<a href=\"dog.jsp?animal=dogfood\" class=\"btn\">Food</a> <a\r\n");
      out.write("				href=\"dog.jsp?animal=dogaccessories\" class=\"btn\">Accessories</a> <a\r\n");
      out.write("				href=\"dog.jsp?animal=doggrooming\" class=\"btn\">Grooming</a> <a\r\n");
      out.write("				href=\"dog.jsp?animal=dogtreats\" class=\"btn\">Treats</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"logos\">\r\n");
      out.write("			<a href=\"Cat.jsp?animal=catfood\"><img src=\"Images1/catlogo.png\"\r\n");
      out.write("				alt=\"Dog Logo\"></a> <a href=\"Bird.jsp?animal=Birds\"><img\r\n");
      out.write("				src=\"Images1/birdlogo.jpeg\" alt=\"Bird Logo\"></a> <a\r\n");
      out.write("				href=\"Fish.jsp?animal=fish\"><img src=\"Images1/fishlogo.jpeg\"\r\n");
      out.write("				alt=\"Fish Logo\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"product-container\">\r\n");
      out.write("\r\n");
      out.write("			");

            Registration r = new Registration(session);
            ArrayList<Dproduct> al = r.get_productinfo(request.getParameter("animal"));
            if (al != null && !al.isEmpty()) {
                for (Dproduct s : al) {
        	
      out.write("\r\n");
      out.write("			<div class=\"product-card\">\r\n");
      out.write("				<div class=\"product-image\">\r\n");
      out.write("					<a href=\"productDetails.jsp?p_id=");
      out.print( s.getp_id() );
      out.write("\"> <img\r\n");
      out.write("						src=\"Images/");
      out.print( s.getp_image() );
      out.write("\" alt=\"");
      out.print( s.getp_name() );
      out.write("\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<h2 class=\"product-title\">");
      out.print( s.getp_name() );
      out.write("</h2>\r\n");
      out.write("				<p class=\"price\">\r\n");
      out.write("					&#8377;\r\n");
      out.write("					");
      out.print( s.getP_cost() );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("				<p class=\"availability\">In Stock</p>\r\n");
      out.write("				<p class=\"delivery-info\">Free shipping on orders over &#8377;\r\n");
      out.write("					1000!</p>\r\n");
      out.write("				<form action=\"addtocart\" method=\"post\" style=\"width: 100%;\">\r\n");
      out.write("					<input type=\"hidden\" name=\"p_id\" value=\"");
      out.print( s.getp_id() );
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("					");
 if(session.getAttribute("uname") != null) { 
      out.write("\r\n");
      out.write("					<div class=\"button-container\">\r\n");
      out.write("						<button name=\"addtocart\" class=\"add-to-cart\">Add to Cart</button>\r\n");
      out.write("						<select name=\"quantity\" id=\"quantity-");
      out.print( s.getp_id() );
      out.write("\"\r\n");
      out.write("							class=\"quantity-select\">\r\n");
      out.write("							");
 for (int i = 1; i <= 7; i++) { 
      out.write("\r\n");
      out.write("							<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
      out.write("							");
 } 
      out.write("\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("					<p style=\"text-align: center;\">Please log in to add items to\r\n");
      out.write("						your cart.</p>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</form>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			");

                }
            } else {
        
      out.write("\r\n");
      out.write("			<p>Shop By categories</p>\r\n");
      out.write("			");

            }
        
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
