/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-05-05 12:54:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Header1.jsp", Long.valueOf(1746446599247L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Registration Form</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.21.0/jquery.validate.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Arial', sans-serif;\r\n");
      out.write("       \r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        background-image:url('Images1/CatBackground.jpg');\r\n");
      out.write("    background-position:fixed;\r\n");
      out.write("    background-repeat:no-repeat;\r\n");
      out.write("    background-size:cover;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("        width: 450px;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("        margin-left:50px;\r\n");
      out.write("        background-color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        box-shadow: 0px 15px 30px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        backdrop-filter: blur(5px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("        color: #f57c00;\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        font-family: 'Comic Sans MS', cursive, sans-serif;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #msg {\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        background-color: #fff9c4;\r\n");
      out.write("        color: #f57c00;\r\n");
      out.write("        border: 1px solid #ffeb3b;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        font-family: 'Comic Sans MS', cursive, sans-serif;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    td {\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        color: #f57c00;\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"text\"],\r\n");
      out.write("    input[type=\"tel\"],\r\n");
      out.write("    input[type=\"email\"],\r\n");
      out.write("    input[type=\"password\"] {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        margin-top: 3px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        border: 2px solid #ffd54f;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"text\"]:focus,\r\n");
      out.write("    input[type=\"tel\"]:focus,\r\n");
      out.write("    input[type=\"email\"]:focus,\r\n");
      out.write("    input[type=\"password\"]:focus {\r\n");
      out.write("        outline: none;\r\n");
      out.write("        border-color: #ff9800;\r\n");
      out.write("        box-shadow: 0 0 8px rgba(255, 152, 0, 0.5);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"submit\"] {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 14px;\r\n");
      out.write("        background-color: #ffeb3b;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"submit\"]:hover {\r\n");
      out.write("        background-color: #f57c00;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login {\r\n");
      out.write("        margin-top: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login a {\r\n");
      out.write("        color: #f57c00;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login a:hover {\r\n");
      out.write("        text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 480px) {\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            padding: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"submit\"] {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;300&display=swap');\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 15px 30px;\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .logo img {\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    width: auto;\r\n");
      out.write("    margin-left:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul li a {\r\n");
      out.write("    padding: 10px 15px;\r\n");
      out.write("    font-size:16px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    \r\n");
      out.write("    color: #333;\r\n");
      out.write("    border-bottom: 2px solid transparent;\r\n");
      out.write("    transition: color 0.3s, border-color 0.3s, transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .menu ul li a:hover {\r\n");
      out.write("    color: #007bff;\r\n");
      out.write("    border-color: #007bff;\r\n");
      out.write("    transform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right i {\r\n");
      out.write("    font-size: 26px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right .rel {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .header_right .rel .num {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: -10px;\r\n");
      out.write("    background-color: red;\r\n");
      out.write("    color: white;\r\n");
      out.write("    width: 16px;\r\n");
      out.write("    height: 16px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uname {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("   \r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("button.btn {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.btn:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    header {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu ul {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        gap: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .header_right {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu ul li a {\r\n");
      out.write("        padding: 12px 20px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <a href=\"Home1.jsp\">\r\n");
      out.write("            <img src=\"Images/Logo.png\" alt=\"Logo\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            ");
 if (session.getAttribute("uname") != null) { 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Home1.jsp\">Home</a></li>\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Contact.jsp\">Contact</a></li>\r\n");
      out.write("\r\n");
      out.write("                <!-- Admin-specific Menu Items (id = 1) -->\r\n");
      out.write("                ");
 if ("1".equals(session.getAttribute("id"))) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"myorder.jsp\">My Orders</a></li>\r\n");
      out.write("                    <li><a href=\"Admin.jsp\">Dashboard</a></li>\r\n");
      out.write("                    <li><a href=\"BookedProducts.jsp\">Booked Products</a></li>\r\n");
      out.write("                    <li><a href=\"UserReviews.jsp\">User Reviews</a></li>\r\n");
      out.write("                    <li><a href=\"AppList.jsp\">Appointment List</a></li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                 \r\n");
      out.write("                    <li><a href=\"HealthAssist.jsp\">Health Assistance</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"register?logout=yes\">Logout</a></li>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Home1.jsp\">Home</a></li>\r\n");
      out.write("                \r\n");
      out.write("                <li><a href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("                <li><a href=\"Registration.jsp\">Register</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("       ");
 if (session.getAttribute("uname") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"header_right\">\r\n");
      out.write("        <a href=\"Wishlist.jsp\"><i class=\"fa fa-heart\"></i></a>\r\n");
      out.write("        <a href=\"Search.jsp\"><i class=\"fa-solid fa-magnifying-glass\"></i></a>\r\n");
      out.write("        <div class=\"rel\">\r\n");
      out.write("            <a href=\"cart.jsp\"><i class=\"fa-solid fa-cart-shopping\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("            <div class=\"uname\">\r\n");
      out.write("                <i class=\"fa fa-user-circle\" style=\"margin-right: 5px;\"></i>\r\n");
      out.write("                ");
      out.print( session.getAttribute("uname") );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("  \r\n");
      out.write("<script>\r\n");
      out.write("    jQuery.validator.addMethod(\"checkemail\", function(value, element) {\r\n");
      out.write("        return /^(([^<>()[\\]\\\\.,;:\\s@\\\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\\\"]+)*)|(\\\".+\\\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$/.test(value) || /^[0-9]{10}$/.test(value); \r\n");
      out.write("    });\r\n");
      out.write("   \r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("    	$(\".container\").hide();\r\n");
      out.write("    	$(\".container\").slideDown(1000);\r\n");
      out.write("        $(\"#signup\").validate({\r\n");
      out.write("            rules: {\r\n");
      out.write("                name: {\r\n");
      out.write("                    required: true\r\n");
      out.write("                },\r\n");
      out.write("                phone: {\r\n");
      out.write("                    required: true,\r\n");
      out.write("                    minlength: 10,\r\n");
      out.write("                    maxlength: 10,\r\n");
      out.write("                    digits: true\r\n");
      out.write("                },\r\n");
      out.write("                email: {\r\n");
      out.write("                    required: true,\r\n");
      out.write("                    checkemail: true\r\n");
      out.write("                },\r\n");
      out.write("                password: {\r\n");
      out.write("                    required: true,\r\n");
      out.write("                    minlength: 4\r\n");
      out.write("                },\r\n");
      out.write("                confirm: {\r\n");
      out.write("                    required: true,\r\n");
      out.write("                    minlength: 4,\r\n");
      out.write("                    equalTo: \"#password\"\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            messages: {\r\n");
      out.write("                name: {\r\n");
      out.write("                    required: \"Please enter your name\"\r\n");
      out.write("                },\r\n");
      out.write("                phone: {\r\n");
      out.write("                    required: \"Please enter your phone number\",\r\n");
      out.write("                    minlength: \"Your phone number must be exactly 10 digits\",\r\n");
      out.write("                    maxlength: \"Your phone number must be exactly 10 digits\",\r\n");
      out.write("                    digits: \"Please enter a valid phone number\"\r\n");
      out.write("                },\r\n");
      out.write("                email: {\r\n");
      out.write("                    required: \"Please enter your email\"\r\n");
      out.write("                },\r\n");
      out.write("                password: {\r\n");
      out.write("                    required: \"Please enter your password\",\r\n");
      out.write("                    minlength: \"Your password must be at least 4 characters long\"\r\n");
      out.write("                },\r\n");
      out.write("                confirm: {\r\n");
      out.write("                    required: \"Please confirm your password\",\r\n");
      out.write("                    minlength: \"Your password must be at least 4 characters long\",\r\n");
      out.write("                    equalTo: \"Passwords do not match\"\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            submitHandler: function(form) {\r\n");
      out.write("                form.submit();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"container\" id=\"container\">\r\n");
      out.write("    <h2>Registration Form</h2>\r\n");
      out.write("\r\n");
      out.write("    ");
 if(request.getAttribute("status") != null) { 
      out.write("\r\n");
      out.write("        <div id=\"msg\">");
      out.print( request.getAttribute("status") );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"register\" id=\"signup\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>NAME</td>\r\n");
      out.write("                <td><input type=\"text\" id=\"name\" name=\"name\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>PHONE NUMBER</td>\r\n");
      out.write("                <td><input type=\"tel\" name=\"phone\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>EMAIL</td>\r\n");
      out.write("                <td><input type=\"email\" name=\"email\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>PASSWORD</td>\r\n");
      out.write("                <td><input type=\"password\" name=\"password\" id=\"password\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>CONFIRM PASSWORD</td>\r\n");
      out.write("                <td><input type=\"password\" name=\"confirm\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\">\r\n");
      out.write("                    <input type=\"submit\" name=\"register\" value=\"Register\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"login\" id=\"container\">\r\n");
      out.write("            <a href=\"Login.jsp\">Already have an Account? Click here for Login</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
