-- CASE STATEMENTS

-- IT IS USED TO PASS CERTAIN CONDITIONS WHILE DISPLAYING THE RECORDS

-- SYNTAX
-- ------
-- SELECT CASE
-- 			WHEN CONDITION_1 THEN VALUE_1
--             WHEN CONDITION_1 THEN VALUE_1
--             .
--             .
--             .
--             WHEN CONDITION_N THEN VALUE_N
--             ELSE DEFAULT_VALUE
-- 		END AS ALIAS_NAME
-- FROM TABLE_NAME

--  1]FNAME AND IF GENDER='M' PRINT SIGMA MALE
					-- GENDER='F' PRINT DAD LITTLE PRINCES
                    --  ELSE OTHERS 
                    
SELECT FNAME ,CASE
				WHEN GENDER='M' THEN 'SIGMA_MALE'
                WHEN GENDER='F' THEN 'DAD_LITTLE_PRINCES'
                ELSE 'OTHERS'
			END AS NICK_NAME
FROM EMPS;

-- WHO BORN BEFORE 2020 AS SENIOR ELSE JUNIOR 
SELECT FNAME ,DOJ,CASE
				WHEN 2020>YEAR(DOJ) THEN 'SENIOR'
                ELSE 'JUNIOR'
			END AS ROLE
FROM EMPS;