-- DEPENDENCY
-- ----------
-- IF ONE ATRIIBUTES DEPENDS ON ANOTHER ATRRIBUTES THEN THE PROCESS WILL BE KNOW AS DEPENDENCY

-- TYPES
-- -------
-- 1.TOTAL FUNCTIONAL DEPENDENCY
-- 2.PARTIAL FUNCTIONAL DEPENDENCY
-- 3.TRANSITIVE FUNCTIONAL DEPENDENCY
