-- 1] CAN WE ABLE TO CREATE DUPLICATE TABLE   // YES


-- SYNTAX
--  CREATE TABLE NEW_TABLE_NAME(SELECT * FROM COPYING_TABLE_NAME);

CREATE TABLE EMPS1(SELECT * FROM EMPS);
SHOW TABLES;


-- 2]  CAN WE ABLE TO CREATE DUPLICATE TABLE WITHOUT RECORDS   // YES

-- SYNTAX
--  CREATE TABLE NEW_TABLE_NAME(SELECT * FROM COPYING_TABLE_NAME WHERE FALSE_CONDITION);

CREATE TABLE EMPS2(SELECT * FROM EMPS WHERE EID=100);
SHOW TABLES;
DESC EMPS1;
SELECT * FROM EMPS1;
SELECT * FROM EMPS2;
DESC EMPS2;



-- 3]  CAN WE ABLE ADD RECORDS FROM ONE TABLE TO ANOTHER TABLE  // YES <BUT> TABLE STRUCTURE MUST BE SAME 

-- SYNTAX
--  INSERT INTO NEW_TABLE_NAME(SELECT * FROM COPYING_TABLE_NAME WHERE CONDITION);


 INSERT INTO EMPS2(SELECT * FROM EMPS WHERE JOB='DELIVERY');
 -- INSERT INTO EMPS2(SELECT * FROM EMPS WHERE CITY='MUMBAI'); // ERROR MISMATCH
SELECT * FROM EMPS2;



CREATE TABLE WAITER_DATA(SELECT * FROM EMPS WHERE JOB='WAITER') ;
SELECT * FROM WAITER_DATA;
-- CREATE TABLE WAITER_DATA(SELECT * FROM EMPS WHERE EID=100) (SELECT * FROM EMPS WHERE JOB='WAITER');
UPDATE EMPS SET SAL=1000
WHERE FNAME='JAHNAVI';














