-- TCL
-- -----------
-- 1.COMMIT
-- 2.ROLLBACK
-- 3.SAVEPOINT

-- 1.COMMIT
-- ---------
-- IT IS USED TO SAVE ALL THE TRANSACTION PERMANENTLY INSIDE DATABASE
-- IN MY SQL ---- COMMIT IS DEFAULT ON
-- IN OTHER SQL --COMMIT IS DEFAULT OFF U EXPLICITLY GIVE COMMIT AT LAST
insert into employee values(1,'YASH'),(2,'SUDEEP');

-- 2.ROLLBACK
-- -----------------
-- IT IS USED TO ROLL OUT THE OPERATION UPTO PREVIOUSLY USED COMMIT STATEMENT
-- SYNTAX
-- ROLLBACK; 

-- WE CAN GET BACK TRANSACTION TILL COMMIT STATEMENT


-- 3.SAVEPOINT
-- ----------------
-- IT IS USED TO MARK ONE POSOTION BETWEEN THE TRANSACTION 
-- ->HERE DATA WILL BE STORED TEMPARARILLY  BUT NOT PERMANENTLY INSIDE THE DATABASE.
-- SYNTAX-
-- -----------
-- SAVEPOINT SAVEPOINT_NAME;

-- WE CAN ROLLOUT THE TRANSACTIONS UPTO CERTAIN SAVEPOINT NOT COMMIT SATATEMENT

-- EXAMPLE--
-- ROLLBACK TO SAVEPOINT_NAME;















 